---
- name: Create a Point to multi-point network
      syntropy_network:
        name: p2m-network
        topology: p2m
        state: present
        connections:
          node:
            state: present
            type: endpoint
            connect_to:
              monitoring:
                type: tag
                state: present

