{
 "title": "Chainlink status",
 "time": { "from": "now-2d", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Seconds since last ethereum block",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "geth_seconds_last_block" }
   ]
  },
  {
   "title": "Ethereum block height",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "geth_block" }
   ]
  },
  {
   "title": "Ethereum wallet balance",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 11, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "eth_balance" }
   ]
  },
  {
   "title": "Failed transaction count",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "tx_manager_tx_attempt_failed" }
   ]
  },
  {
   "title": "Ethereum gas price",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "sci" } },
   "yaxes": [
    { "format": "sci" }
   ],
   "targets": [
    { "expr": "geth_gas_price" }
   ]
  },
  {
   "title": "Failed statistics retrievals",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "promhttp_metric_handler_requests_total{code =~ \"503|500\"}",
     "legendFormat": "Error code {{code}} requests on {{job}}"
    }
   ]
  },
  {
   "title": "Database status",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 11 },
   "targets": [
    { "expr": "pg_up", "legendFormat": "{{job}}" }
   ]
  }
 ]
}