{
 "title": "Elrond Validator",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Elrond syncing status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "erd_is_syncing" }
   ]
  },
  {
   "title": "Current round",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "erd_current_round" }
   ]
  },
  {
   "title": "Count of transactions processed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "erd_num_transactions_processed",
     "legendFormat": "Count of transactions processed"
    }
   ]
  },
  {
   "title": "Elrond Node memory load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "erd_mem_load_percent", "legendFormat": "Memory load (%)" }
   ]
  },
  {
   "title": "Elrond network traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "erd_network_sent_bps", "legendFormat": "Sent bytes/sec" },
    { "expr": "erd_network_recv_bps", "legendFormat": "Received bytes/sec" }
   ]
  },
  {
   "title": "Elrond Node CPU load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "erd_cpu_load_percent", "legendFormat": "CPU load (%)" }
   ]
  }
 ]
}