- name: launch node exporter
  docker_container:
    name: "exporter"
    image: jvstein/bitcoin-prometheus-exporter:latest
    env:
      #BITCOIN_RPC_HOST: bitcoind
      #BITCOIN_RPC_USER: "alice"
      #BITCOIN_RPC_PASSWORD: "password=123&z!=@e"
      BITCOIN_CONF_PATH: /etc/bitcoin/bitcoin.conf
      REFRESH_SECONDS: "1"
      LOG_LEVEL: "INFO"
    ports:
      - "8334:8334"
    volumes:
    - /home/bitcoin/config/bitcoin.conf:/etc/bitcoin/bitcoin.conf
    network_mode: "syntropy_network"
    networks: 
      - name: "syntropy_network"
        ipv4_address: "10.51.2.6"
    detach: yes