---
name: blockchain
state: present
topology: p2m
connections:
  monitoring_node:
    connect_to:
      ethereum_nodes:
        type: tag
        services:
          - beacon-node
          - validator
    state: present
    type: endpoint 
    services:
      - prometheus
      - grafana
  localhost:
    connect_to:
      ethereum_node:
        type: tag
        services:
          - beacon-node
          - validator
      monitoring_node:
        type: endpoint
        services:
          - prometheus
          - grafana
    state: present
    type: endpoint